#!/usr/bin/env python3
from __future__ import annotations

import base64
import json
import os
import re
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

USERNAME = "zeiddata-dev"
PROFILE_REPO = "zeiddata-dev/zeiddata-dev"
README_PATH = "README.md"

START = "<!-- ZD_NOW_BUILDING_START -->"
END = "<!-- ZD_NOW_BUILDING_END -->"

TOKEN = os.environ.get("GITHUB_TOKEN", "").strip()
if not TOKEN:
    raise SystemExit("[FAIL] GITHUB_TOKEN missing")

def api(method: str, path: str, body: dict | None = None):
    url = f"https://api.github.com{path}"
    data = None
    headers = {
        "Accept": "application/vnd.github+json",
        "Authorization": f"Bearer {TOKEN}",
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": "zeid-data-profile-updater",
    }

    if body is not None:
        data = json.dumps(body).encode("utf-8")
        headers["Content-Type"] = "application/json"

    req = urllib.request.Request(url, data=data, headers=headers, method=method)

    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            raw = resp.read().decode("utf-8")
            return json.loads(raw) if raw else {}
    except urllib.error.HTTPError as e:
        detail = e.read().decode("utf-8", errors="replace")
        raise SystemExit(f"[FAIL] GitHub API {method} {path}: HTTP {e.code}\n{detail}")

def short_time(value: str | None) -> str:
    if not value:
        return "unknown"
    try:
        dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
        return dt.strftime("%Y-%m-%d")
    except Exception:
        return value[:10]

def clean_commit_message(message: str) -> str:
    first = message.splitlines()[0].strip()
    first = re.sub(r"\s+", " ", first)
    if len(first) > 90:
        first = first[:87] + "..."
    return first or "Recent update"

def latest_commit(full_name: str) -> tuple[str, str]:
    commits = api("GET", f"/repos/{full_name}/commits?per_page=1")
    if not commits:
        return "No commits found", "unknown"

    commit = commits[0].get("commit", {})
    message = clean_commit_message(commit.get("message", "Recent update"))
    date = commit.get("committer", {}).get("date") or commit.get("author", {}).get("date")
    return message, short_time(date)

def build_now_building() -> str:
    repos = api("GET", f"/users/{USERNAME}/repos?sort=pushed&direction=desc&per_page=12")

    selected = []
    for repo in repos:
        if repo.get("fork") or repo.get("archived"):
            continue
        if repo.get("name") == USERNAME:
            continue

        selected.append(repo)
        if len(selected) >= 6:
            break

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        START,
        "## Now Building",
        "",
        f"_Auto-updated from recent GitHub activity: {now}_",
        "",
        "| Repo | Latest signal | Updated |",
        "|---|---|---|",
    ]

    for repo in selected:
        full_name = repo["full_name"]
        name = repo["name"]
        url = repo["html_url"]
        pushed = short_time(repo.get("pushed_at"))
        try:
            message, commit_date = latest_commit(full_name)
            updated = commit_date if commit_date != "unknown" else pushed
        except Exception:
            message = repo.get("description") or "Recent repository activity"
            updated = pushed

        lines.append(f"| [{name}]({url}) | {message} | {updated} |")

    if not selected:
        lines.append("| [Research](https://github.com/zeiddata-dev/Research) | No recent public repository activity found. | unknown |")

    lines.extend([
        "",
        "<sub>Generated by `.github/workflows/update-now-building.yml`. If this section looks boring, the robot is either sleeping or nothing public moved.</sub>",
        "",
        END,
    ])

    return "\n".join(lines)

def update_readme():
    current = api("GET", f"/repos/{PROFILE_REPO}/contents/{README_PATH}?ref=main")
    sha = current["sha"]
    text = base64.b64decode(current["content"]).decode("utf-8", errors="replace")

    block = build_now_building()

    if START in text and END in text:
        new_text = re.sub(re.escape(START) + r".*?" + re.escape(END), block, text, flags=re.DOTALL)
    else:
        new_text = text.rstrip() + "\n\n" + block + "\n"

    if new_text == text:
        print("[PASS] README already current")
        return

    payload = {
        "message": "Update dynamic Now Building section",
        "content": base64.b64encode(new_text.encode("utf-8")).decode("ascii"),
        "sha": sha,
        "branch": "main",
    }

    result = api("PUT", f"/repos/{PROFILE_REPO}/contents/{README_PATH}", payload)
    print("[PASS] updated README")
    print(result.get("commit", {}).get("html_url", ""))

if __name__ == "__main__":
    update_readme()
